language: objective-c
before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail
- xcodebuild -workspace Todo.xcworkspace -scheme Todo test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c

